int is_prime_number(int n);
int check_prime(int n, int resp);
int square(int n, int val);
int _pow_recursion(int x, int y);
int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int factorial(int n);
int _sqrt_recursion(int n);
